app:
    resource: @AppBundle/Controller/
    type:     annotation

# RasmusPackageMateBundle routes (to be removed)
rasmus_package_mate:
    resource: @RasmusPackageMateBundle/Resources/config/routing.yml
