// Each jump for BFS
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX psys:<http://proton.semanticweb.org/protonsys#>
PREFIX ont:<http://adouglas.github.io/onto/php-packages.rdf#>
PREFIX owl:<http://www.w3.org/2002/07/owl#>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX pext:<http://proton.semanticweb.org/protonext#>
SELECT ?startname ?endname (count(?name) as ?link_strength)
WHERE
{
  ?start ont:name "d4rkstar".
  ?start ont:name ?startname.
  ?end ont:name ?endname.
  ?start ont:collaboratesOn ?mid.
  ?mid ont:hasCollaborator ?end.
  ?mid ont:repostoryName ?name.
  FILTER NOT EXISTS
  {
    ?end ont:name ?startname.
  }
}GROUP BY ?startname ?endname


// Solve using a depth limited breadth first search
// Then rank by depth and link strength
// Could be improved by prioritising by link strength when traversing
